[package]
name = "rust_ping_pong_udp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "first"
path = "src/first.rs"

[[bin]]
name = "second"
path = "src/second.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }